<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>C:\Users\hamza\Desktop\Offensive\Evasion\Dev\Washmachine\bin\</BaseOutputPath>
    <RootNamespace>Washmachine</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <SignAssembly>False</SignAssembly>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>

</Project>
